BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Log In') BBBBBBBB

BBBBB BBBB

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXXX XXXXXXX  gettext(u'Log In') XXXXX

      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXXBBBBBBBBBB

        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        BB BBBBBBBBBBBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
        BBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Log In') XXXXXXXXX
      XXXXXXX

      XXXX
      XX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot Password') XXXXX
      XXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u"Don't have an account yet") XXXXX

    XXXXXX XXXXXXXXXXXXXX
  XXXXXX XXXXXXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXX

BBBBBBBB BBBB
