BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Sign Out') BBBBBBBB

BBBBB BBBB

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXXX XXXXXXX  gettext(u'Sign Out') XXXXX

      XXX gettext(u'Are you sure you want to sign out') XXXXX

      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXXBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
        BBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Out') XXXXXXXXX
      XXXXXXX

    XXXXXX XXXXXXXXXXXXXX
  XXXXXX XXXXXXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXX

BBBBBBBB BBBB
