BBBBBBB BBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBB
    XXX XXXXXXXXXXXX XXXXXX gettext(u'Change Password') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB

	XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

	XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

	XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Change Password') XXXXXXXXX

	XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot Password?') XXXX
    XXXXXXX
BBBBBBBB
