BBBBBBB BBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Password Reset') BBBBBBBB

BBBBB BBBB
    XXX XXXXXXXXXXXX XXXXXX gettext(u'Password Reset') XXXXX
    
    BB BBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
    
    XXX gettext(u'We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.') SS SSSS SSSS SSS SS SSSSSSS SSSSSS SSSSSSS SS SS SSS SS SSS SSSSSSS SS SSSSSS S SSS SSSSSSSSXXXX
BBBBBBBB
