BBBBBBB BBBBBBBBBBB

BBBB BBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Password Reset') BBBBBBBB

BBBBB BBBB

    XXX XXXXXXXXXXXX XXXXXX gettext(u'Password Reset') XXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB

    XXX gettext(u"Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.") XXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB

	XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Reset My Password') X XX
    XXXXXXX

    XXX gettext(u'Please contact us if you have any trouble resetting your password.') SSSSSS SSSSSSS SS SS SSS SSSS SSS SSSSSSS SSSSSSSSS SSSS SSSSSSSSSXXXX
BBBBBBBB
