BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBB
    XXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBB gettext(u'Bad Token') BBBB gettext(u'Change Password') BBBBBXXXXX

    BB BBBBBBBBBB
        BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
        XXX gettext(u'The password reset link was invalid, possibly because it has already been used.  Please request a <a href="%(passwd_reset_url)s">new password reset</a>.') SSS SSSSSSSS SSSSS SSSS SSS SSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSSSS SSSS SSSSS  SSSSSS SSSSSSS S SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSXXXX
    BBBB
        BB BBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXBBBBBBBBBB
	      XXXX XXXXXXXXXXXXXX
	        XXXX XXXXXXXXXXXXXXXX
		  BB BBBBBBBBBBBBBBBBBBBBB
		    BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
		      XX XXXXXXXXXXX XXXXXXXXXXXXXXX
		    BBBBBB
		  BBBB
		    BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		    XX XXXXXXXXXXXXXXXXX
		  BBBBB
	        XXXXXX
	      XXXXXX

	      XXXX XXXXXXXXXXXXXX
	        XXXX XXXXXXXXXXXXXXXX
		  BB BBBBBBBBBBBBBBBBBBBBB
		    BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
		      XX XXXXXXXXXXX XXXXXXXXXXXXXXX
		    BBBBBB
		  BBBB
		    BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		    XX XXXXXXXXXXXXXXXXX
		  BBBBB
	        XXXXXX
	      XXXXXX

	      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Change password') XXX
            XXXXXXX
        BBBB
            XXX gettext(u'Your password is now changed.') XXXX
        BBBBB
    BBBBB
BBBBBBBB
