# Generated by Django 3.1 on 2020-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alternative'),
        ('users', '0003_auto_20201023_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alternatives_chosen',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alternatives_chosen',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='questions.Alternative'),
        ),
    ]
