# Generated by Django 3.1 on 2021-01-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='alternative',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
