# Generated by Django 3.1 on 2021-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210323_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='image',
            field=models.ImageField(
                default='default_alternative.jpg', upload_to='profile_pics'
            ),
        ),
    ]
