# Generated by Django 3.1 on 2021-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210303_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
