# Generated by Django 3.1 on 2021-04-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210401_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='image',
            field=models.ImageField(blank=True, default='default_alternative.jpg', upload_to='alternative_pics'),
        ),
    ]
