# Generated by Django 3.1 on 2021-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210402_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='image',
            field=models.ImageField(
                default='default_alternative.jpg', upload_to='alternative_pics'
            ),
        ),
    ]
