# Generated by Django 3.1 on 2021-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210402_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='attribution',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                null=True,
                verbose_name='credit for the image',
            ),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='image',
            field=models.ImageField(
                default='default_alternative.png', upload_to='alternative_pics'
            ),
        ),
    ]
