# Generated by Django 3.1 on 2021-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='shared_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
