# Generated by Django 3.1 on 2021-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_shared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='shared_by',
            field=models.CharField(
                blank=True, default='', max_length=100, null=True
            ),
        ),
    ]
