# Generated by Django 3.1 on 2021-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
