# Generated by Django 3.1 on 2021-03-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
