# Generated by Django 3.1 on 2021-03-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_questionlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
