# Generated by Django 3.1 on 2021-03-25 02:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('lists', '0003_auto_20210318_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
