# Generated by Django 3.1 on 2021-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20210308_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='description',
            field=models.TextField(
                blank=True, max_length=200, verbose_name='description'
            ),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
