# Generated by Django 3.1 on 2021-03-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_questionlist_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='description',
        ),
    ]
