# Generated by Django 3.1 on 2021-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_remove_questionlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
