BBBBBBB BBBBBBBBBBB

BBBB BBBB
BBBB BBBB
BBBB BBBBBB

BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXX X BBBBBBBB


BBBBB BBBB

  BBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBB BB BBBBBBBB
  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXX

      XXXX XXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
      XXXXXX XXXX XXXX XXX

      XXXX XXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXX XXXXX XXX

    XXXXXX
  BBBBBBB

  BBBBBBBB BBB
    XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX
  BBBBBBBBBBB

  XXX XXXXXXXXXXXX XXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXBBBBB
      XXXX XXXXXXXXXXXXX XXXXXX

	XXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX

	  XXXX XXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX

	      XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX
              XXXXXXXXX

              XXXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX
	          XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                BBBB
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX
	          XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                BBBBB
              XXXXXXXXX
            XXXXXX

          XXXXXX XXXX XXXX XXXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXXXX
	    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Vote') XXXXXXXXX
          XXXXXXXXX

	XXXXXX XXXX XXXX XXX

      XXXXXX XXXX XXX XXXX XXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
      BB BBBBBBBBBBBBXXXXXXBBBBB

  BBBBBB

BBBBBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBBBB
