BBBBBBB BBBBBBBBBBB

BBBB BBBB
BBBB BBBB
BBBB BBBBBB

BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXX X BBBBBBBB


BBBBB BBBB

  BB BBBBBBBBBBBBBBBBBBBBB
    BBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBB BB BBBBBBBB
  BBBB
    BBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BB BBBBBBBB
  BBBBB
  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXX

      XXXX XXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
      XXXXXX XXXX XXXX XXX

      XXXX XXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXX XXXXX XXX

    XXXXXX
  BBBBBBB

  BBBBBBBB BBB
    XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX
  BBBBBBBBBBB

  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXX gettext(u'You are <b>seeing this</b> message because you are <b>not logged in</b>') XXXXX
      BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
      BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
      XXX gettext(u'<a href="%(account_signup)s">Create an account</a> (it will take you like 10 seconds, unless you are robot 🤖) or <a href="%(account_login)s">log in</a> to get access to all the features.') SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSS SSS SSSS SSSS SSS SSSS SS SSSSSSSS SSSSSS SSS SSS SSSSS SS SS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS SS SSS SSSSSS SS SSS SSS SSSSSSSSSXXXX
      XXX gettext(u'By using an account you get to') XXXXX
      XXXX  gettext(u'Vote in every list') XXXXX
      XXXX  gettext(u'Create lists.') XXXX
      XXXX  gettext(u'See the results of lists and see what your friends have voted') XXXXX
      XX XXXXXXXXXXXXXX  gettext(u'This is and much more') XXXXX
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXX  gettext(u'Sign Up') XXXX
      XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXX  gettext(u'Log In') XXXX
      XX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBXX gettext(u'Play a demo list') XXXX
    XXXXXX
  XXXXXXXXXX

  XXX XXXXXXXXXXXX XXXXXXXXXXX

  BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXBBBBB
      XXXX XXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXXXX
	    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX

	  XXXX XXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                BBBB
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                BBBBB
              XXXXXXXXX
            XXXXXX

          XXXXXX XXXX XXXX XXXXXXXXXX

          XXXXXXX XXXXXXXXXXXXXXXXXXXX
	    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX gettext(u'Vote') XXXXXXXXX
          XXXXXXXXX

	XXXXXX XXXX XXXX XXX

      XXXXXX XXXX XXX XXXX XXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
      BB BBBBBBBBBBBBXXXXXXBBBBB

  BBBBBB

BBBBBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBBBB
