BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXX X XXXXBBBBBBBB

BBBBB BBBB

XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXXX XXXXXX gettext(u'Create a list') XXXXX
      XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB

        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBB
              BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
            BBBB
              BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
	      XX XXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX
        XXXXXX

	XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX
	    
	    BB BBBBBBBBBBBBBBBBBBB
	      BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
	        XX XXXXXXXXXXX XXXXXXXXXXXXXXX
	      BBBBBB
	    BBBBB
          XXXXXX
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Create') XXXXXXXXX
      XXXXXXX

    XXXXXX XXXXXXXXXXXXXX
  XXXXXX XXXXXXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXX

BBBBBBBB BBBB
