# Generated by Django 3.1 on 2021-04-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('child_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='demo.demolist')),
            ],
        ),
        migrations.CreateModel(
            name='DemoAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_alternative.png', upload_to='alternative_pics')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='demo.demoquestion')),
            ],
        ),
    ]
